# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate challenges

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install yarn
      run: npm install --global yarn
    - name: Install dependencies
      run: yarn
      
    - name: Run resolved challenges
      run: |
        yarn run unstoppable
        yarn run naive-receiver
        yarn run truster
        yarn run side-entrance
        yarn run the-rewarder
        yarn run selfie
        yarn run compromised
    
